--- 
# Criando os containers
- name: "Criando o diretorio local do volume"
  file: |
    path: "{{ host_dir_volume }}"
    state: directory
    owner: "{{ container_user_id }}"
    group: "{{ container_group_id }}"
    mode: "{{ permissions }}"    

- name: "Criando o conteiner {{ container_name }} "
  docker_container:
    name: "{{ container_name }}"
    image: "{{ container_image }}"
    detach: yes
    volumes:
      - "{{ host_dir_volume }}:{{ container_dir_volume }}"
    restart_policy: "{{ container_restart_policy }}"
    ports:
          - "{{ host_port }}:{{ container_port }}"
    env:
      GF_INSTALL_PLUGINS: "{{ grafana_plugins }}"
      GF_SERVER_PROTOCOL: "{{ grafana_protocol }}"
      GF_SERVER_HTTP_PORT: "{{ container_port }}"