---

- name: 1 - Criando o(s) servidor(es) de monitoramento
  hosts: monitoring
  vars_files: 
    - vars/variables_general.yml
    - vars/groups/monitoring.yml    
  roles:
    - docker

  tasks:  
    - name: Instalando o Python e Python-PIP
      package: name=python,python-pip state=latest
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '18.04'

    - name: Instala o modulo Docker para Python
      pip:
        name: docker

    - name: Executando a role que cria o conteiner do Grafana
      include_role:
        name: container_grafana

    - name: Executando a role que cria o conteiner do Prometheus
      include_role:
        name: container_prometheus

    - name: Executando a role que cria os conteineres do Zabbix-Server, Zabbix-Web, Zabbix-Agent e MySQL
      include_role:
        name: container_zabbix